### ISSUE TITLE
[0.1.2] Error on installation

### ISSUE THREAD

**Issue by mdjurfeldt** [jneilliii/OctoPrint-MQTTSubscribe#10]
When installing branch 0.1.2, commit cd03ac1 (using https://github.com/jneilliii/OctoPrint-MQTTSubscribe/archive/0.1.2.zip in plugin manager) in a scratch installation of OctoPrint, the following error is reported in the log:

2020-02-09 17:56:17,096 - octoprint.plugin - ERROR - Error while calling plugin mqttsubscribe
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/plugin/__init__.py", line 219, in call_plugin
    result = getattr(plugin, method)(*args, **kwargs)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_mqttsubscribe/__init__.py", line 79, in on_after_startup
    self.mqtt_subscribe(topic["topic"], self._on_mqtt_subscription)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_mqtt/__init__.py", line 389, in mqtt_subscribe
    self._mqtt.subscribe(topic)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 1479, in subscribe
    raise ValueError('Invalid topic.')

**Comment by jneilliii** [comment]
That makes sense because the default values are loaded with a blank topic.  When I do my changes for the UI improvements it will fix this.
